export { default as RemoteDesktop } from './RemoteDesktopShare/views/RemoteDesktopView.jsx';
export { default as Deployfy } from './Deployfy/views/DeployfyView.jsx';
export { default as FileSharing } from './FIleSharing/views/FileSharingView.jsx';
export { default as PrivateCoding } from './PrivateCodingEnvironment/views/PrivateCodingView.jsx';
export { default as CollaborativeCoding } from './CollaborativeCodingEnvironment/views/CollaborativeCodingView.jsx';
export { default as MeetingHandler } from './MeetingHandler/views/MeetingHandlerView.jsx';
export { default as VideoStreaming } from './LiveStreamingView/views/LiveStreamingView.jsx';
export { default as VirtualWhiteboard } from './VirtualWhiteboard/views/VirtualWhiteboardView.jsx';
export { default as TextPad } from './TextPad/views/TextPadView.jsx';
